spring:
  #环境 dev:开发环境|prod:生产环境
  profiles:
    active: dev #激活的配置文件
  datasource:
    url: #部署数据库地址
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:dataImpl/*/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  max-http-header-size: 102400
  port: 8001

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI4G3YDVKD453rLQRPeAQj # 访问身份验证中用到用户标识
    access-key-secret: zHDmPtPZ6lzTfHWIuMnxdrYvEcSkHM # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucket-name: pyyybf # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    max-size: 10 # 上传文件大小(M)
    prefix: http://pyyybf.oss-cn-shanghai.aliyuncs.com/
    directory:
      root: judgmentDoc/
      avatars: avatars/

directory:
  static:
    fonts:
      simsun: D:/judgmentDoc/backend/src/main/resources/static/fonts/simsun.ttc,1
  temporary: D:/judgmentDoc/backend/src/main/resources/temporary/

model:
  name: model
  url: http://localhost:8000/model
